ignored = [
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

# client-go 7.0.0 uses apimachinery 302974c03f7e50f16561ba237db776ab93594ef6
# and api 73d903622b7391f3312dcbac6483fed484e185f8 (see Godep.json). go dep
# is unable to match Godep.json automatically so have to specify here.
[[constraint]]
    name = "k8s.io/client-go"
    version = "v7.0.0"
[[override]]
    name = "k8s.io/apimachinery"
    revision = "302974c03f7e50f16561ba237db776ab93594ef6"
[[override]]
    name = "k8s.io/api"
    revision = "73d903622b7391f3312dcbac6483fed484e185f8"

# Pin these dependencies to the exact versions listed in the
# Makefile. We can't even allow the patch version to float as that
# then causes compilation errors.
[[override]]
    name = "github.com/mholt/caddy"
    version = "=v0.11.1"

[[override]]
    name = "github.com/miekg/dns"
    version = "=v1.1.3"

[[override]]
    name = "github.com/prometheus/client_golang"
    version = "=v0.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/openshift-metal3/coredns-mdns"
