diff --git a/Makefile b/Makefile
index 6d8cd9189..98a5bc3d3 100644
--- a/Makefile
+++ b/Makefile
@@
 .PHONY: test
-test: check
-	( cd request ; go test -v -race ./... )
-	( cd core ; go test -v -race  ./... )
-	( cd coremain ; go test -v -race ./... )
-	( cd test ; go test -v -race ./... )
-	( cd plugin ; go test -v -race ./... )
+test: check
+	GOFLAGS=-mod=vendor go test -count=1 ./...
